server:
  port: 8888

eureka:         
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value(10)}}
      
  client:
    enabled: true
    registerWithEureka: false
    fetchRegistry: false  
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
          
  security:
    user:
      name: config
      password: configpwd$001          
          
  profiles:
     active: native, default, cloud

  