server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
          
  security:
    user:
      name: config
      password: configpwd$001          
          
  profiles:
     active: native, default, cloud

