server:
  port: ${PORT:8888}
  servlet: 
    context-path: /config

eureka:         
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.int}}
      
  client:
    enabled: true
    registerWithEureka: false
    fetchRegistry: false  
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
          
  security:
    user:
      name: config
      password: configpwd$001          
          
  profiles:
     active: native, default, cloud

management: 
    metrics: 
     export: 
        influx: 
          auto-create-db: true
          enabled: true
          db: metrics 
          uri: http://localhost:8086
        prometheus: 
          enabled: true
         
    endpoints:             
      web: 
        exposure: 
          include: /*
                
    endpoint: 
      prometheus: 
        enabled: true           