server:
  port: 8888

eureka:         
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    
  client:
    registerWithEureka: true
    initial-instance-info-replication-interval-seconds: 5
    eureka-service-url-poll-interval-seconds: 5
    should-unregister-on-shutdown: true
    enabled: false
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/registry/
    heartbeat-executor-exponential-back-off-bound: 10
    heartbeat-executor-thread-pool-size: 1
    
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
          
  security:
    user:
      name: config
      password: configpwd$001          
          
  profiles:
     active: native, default, cloud

  