server:
  port: ${PORT:5006}

info:
  component: order.server

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

management: 
    metrics: 
      export: 
        influx:
          enabled: false 
          db: springboot 
          uri: http://localhost:8086
    endpoint: 
      prometheus: 
        enabled: true    
