spring:
  data:
    mongodb:
      host: acount-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: flowersdb
      port: 27017

server:
  context-path: /account
  port: 5001
