logging:
  level:
    org.springframework.security: INFO
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

management: 
    metrics: 
     export: 
        influx: 
          enabled: true
          db: metrics 
          uri: http://localhost:8086
        prometheus: 
          enabled: true
         
    endpoints:             
      web: 
        exposure: 
          include: /*
                
    endpoint: 
      prometheus: 
        enabled: true  