---
server: 
  servlet:
    context-path: /auth

spring:
  profiles: default
  application:
    name: auth-service
    
  client:
    enabled: true  
    serviceUrl: 
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true    
    
management: 
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
        exclude: 
      base-path: /      
  info:
    git:
      mode: full
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true   
       
logging:
    level:
      ROOT: INFO
      org.springframework.web: DEBUG 
      com.flowers.microservice.auth.service: DEBUG      

        