spring:
  data:
    mongodb:
      host: data-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: flowersdb
      port: 27017

server:
  context-path: /database
  port: 5003
