---      
server:
  servlet: 
    context-path: /gateway
    
spring:
  profiles: default
  application:
    name: gateway

eureka:         
  client:
    enabled: true  
    serviceUrl: 
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true    
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.int}}      
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 100
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
            
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
  
    dashboard:
        path: /dashboard/**
        url: dashboard
        stripPrefix: false
        sensitiveHeaders:
          
    auth-service:
        path: /auth/**
        url: http://auth-service:5000
        stripPrefix: false
        sensitiveHeaders:
        
    registry:
        path: /registry/**
        serviceId: registry
        stripPrefix: false
        sensitiveHeaders:

    product-service:
        path: /products/**
        serviceId: product-service
        stripPrefix: false
        sensitiveHeaders:
        
    inventory-service:
        path: /inventory/**
        serviceId: inventory-service
        stripPrefix: false
        sensitiveHeaders:
        
    account-service:
        path: /shipping/**
        serviceId: shipping-service
        stripPrefix: false
        sensitiveHeaders:

    order-service:
        path: /order/**
        serviceId: order-service
        stripPrefix: false
        sensitiveHeaders:
        
    tax-service:
        path: /tax/**
        serviceId: tax-service
        stripPrefix: false
        sensitiveHeaders:        

    notification-service:
        path: /notifications/**
        serviceId: notification-service
        stripPrefix: false
        sensitiveHeaders:
    
management: 
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
        exclude: 
      base-path: /      
  info:
    git:
      mode: full
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true   
        
logging:
    level:
      ROOT: INFO
      org.springframework.web: DEBUG 
      com.flowers.microservice.gateway.controller: DEBUG     
        

