---      
server:
  context-path: /gateway
  port: 4000
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
  
    dashboard:
        path: /dashboard/**
        url: dashboard
        stripPrefix: false
        sensitiveHeaders:
          
    auth-service:
        path: /auth/**
        url: http://auth-service:5000
        stripPrefix: false
        sensitiveHeaders:
        
    registry:
        path: /registry/**
        serviceId: registry
        stripPrefix: false
        sensitiveHeaders:

    product-service:
        path: /products/**
        serviceId: product-service
        stripPrefix: false
        sensitiveHeaders:
        
    inventory-service:
        path: /inventory/**
        serviceId: inventory-service
        stripPrefix: false
        sensitiveHeaders:
        
    account-service:
        path: /shipping/**
        serviceId: shipping-service
        stripPrefix: false
        sensitiveHeaders:

    order-service:
        path: /order/**
        serviceId: order-service
        stripPrefix: false
        sensitiveHeaders:
        
    tax-service:
        path: /tax/**
        serviceId: tax-service
        stripPrefix: false
        sensitiveHeaders:        

    notification-service:
        path: /notifications/**
        serviceId: notification-service
        stripPrefix: false
        sensitiveHeaders:
eureka:         
  instance:
    hostname: localhost
   
  client:
    registerWithEureka: false
    initial-instance-info-replication-interval-seconds: 5
    eureka-service-url-poll-interval-seconds: 5
    should-unregister-on-shutdown: true
    enabled: false
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    heartbeat-executor-exponential-back-off-bound: 10
    heartbeat-executor-thread-pool-size: 1
         
management: 
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
        exclude: 
      base-path: /      
  info:
    git:
      mode: full
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true   
        
logging:
    level:
      ROOT: INFO
      org.springframework.web: DEBUG 

