spring:
  data:
    mongodb:
      host: monitoring-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: flowersdb
      port: 27017

server:
  context-path: /monitoring
  port: 5007