---
server: 
  context-path: /notifications
  port: 8000

eureka:         
  instance:
    hostname: localhost
   
  client:
    registerWithEureka: false
    initial-instance-info-replication-interval-seconds: 5
    eureka-service-url-poll-interval-seconds: 5
    should-unregister-on-shutdown: true
    enabled: false
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/registry/
    heartbeat-executor-exponential-back-off-bound: 10
    heartbeat-executor-thread-pool-size: 1
         
management: 
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
        exclude: 
      base-path: /      
  info:
    git:
      mode: full
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true   
        
logging:
    level:
      ROOT: INFO
      org.springframework.web: DEBUG 
      com.flowers.microservice.order.service: DEBUG      

remind:
  cron: 0 0 0 * * *
  email:
    text: "Hey, {0}! We''ve missed you here on Flowers. It''s time to check your budget statistics.\r\n\r\nCheers,\r\nFlowers team"
    subject: Flowers reminder

backup:
  cron: 0 0 12 * * *
  email:
    text: "Howdy, {0}. Your account backup is ready.\r\n\r\nCheers,\r\nFlowers team"
    subject: Flowers account backup
    attachment: backup.json

spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: dev-user
    password: dev-password
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          ssl:
            enable: true
