spring:
  data:
    mongodb:
      host: order-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: flowersdb
      port: 27017

server:
  context-path: /order
  port: 5006
