---

spring:
  profiles: default
  application:
    name: product-service
    
server:
  context-path: /products
  port: 5008

eureka:         
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value(10)}}
      
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: false  
    serviceUrl:
      defaultZone: http://localhost:8761/registry/
      
discovery:
    enabled: true
    service-id: config-server

management: 
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
        exclude: 
      base-path: /      
  info:
    git:
      mode: full
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true   
        
logging:
    level:
      ROOT: INFO
      org.springframework.web: DEBUG 
      com.flowers.microservice.product.service: DEBUG      

      