---
server:
  context-path: /eureka
  port: 8761
       
eureka:
  instance:
    hostname: localhost
    appname: registry    
  client:
    register-with-eureka: false
    fetch-registry: false    
       
logging:
    level:
      ROOT: INFO
      org.springframework.web: DEBUG 
      com.flowers.microservice.eureka.service: DEBUG