---
server:
  context-path: /registry
  port: 8761
       
eureka:
  instance:
    prefer-ip-address: true
   
  client:
    register-with-eureka: false
    fetch-registry: false
            
management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
        exclude: 
      base-path: /      
  info:
    git:
      mode: full
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true            
       
logging:
    level:
      ROOT: INFO
      org.springframework.web: DEBUG 
      com.flowers.microservice.eureka.service: DEBUG