---
server: 
  context-path: /shipping
  port: 5002

eureka:         
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    
   
  client:
    registerWithEureka: false
    initial-instance-info-replication-interval-seconds: 5
    eureka-service-url-poll-interval-seconds: 5
    should-unregister-on-shutdown: true
    enabled: false
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/registry/
    heartbeat-executor-exponential-back-off-bound: 10
    heartbeat-executor-thread-pool-size: 1
         
management: 
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
        exclude: 
      base-path: /      
  info:
    git:
      mode: full
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true   
        
logging:
    level:
      ROOT: INFO
      org.springframework.web: DEBUG 
      com.flowers.microservice.compute.service: DEBUG      

        