---

spring:
  profiles: default
  application:
    name: shipping-service
    
  client:
    enabled: true  
    serviceUrl: 
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true    
       
  info:
    git:
      mode: full
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true   
        
logging:
    level:
      ROOT: INFO
      org.springframework.web: DEBUG 
      com.flowers.microservice.product.service: DEBUG      

        